fightingGame/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Game screen for laptop
  root 'welcome#index'

  resources :game, only: [:index, :new]
  # welcome page for mobile devices
  resources :welcome, only: [:index, :show]
  # controller pages for players
  resources :players, only: [:show, :create]

end

fightingGame/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fightingGame/app/models/player.rb
class Player < ApplicationRecord
end

fightingGame/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

fightingGame/app/controllers/game_controller.rb
class GameController < ApplicationController


  def index
  end


  def new
  end

end

fightingGame/app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def create
  user_agent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36'
  @player = Player.new(player_form_params)
  @player.ip = request.remote_ip
  client = DeviceDetector.new(user_agent)

  # puts "The country:      #{Geocoder.search('209.171.88.22').first.country}"
  # puts "The country:      #{Geocoder.search('209.171.88.22').first.city}"

    if @player.save
      #not sure about the url of controller
      redirect_to "/controller/:id"
    end

  end


  def show
  end

  private

  def player_form_params
    params.require(:player).permit(:name, :email,)
  end

end

fightingGame/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def show
  end

end

fightingGame/app/helpers/application_helper.rb
module ApplicationHelper
end

fightingGame/app/helpers/game_helper.rb
module GameHelper
end

fightingGame/app/helpers/players_helper.rb
module PlayersHelper
end

fightingGame/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fightingGame/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FightingGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fightingGame/app/views/welcome/index.html.erb
<div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</div>

<!-- <!DOCTYPE HTML>
<html>
<head> -->

    <!-- Set up page info -->
<!--     <meta charset="utf-8" />
    <title>VirtualGamepad Demo</title>
    <meta name="description" content="VirtualGamepad" />
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #000000;
        }
    </style> -->

    <!-- Load libraries and game states -->
<!--     <script src="../assets/javascripts/rubygame/phaser.js.erb"></script>
    <script src="../assets/javascripts/rubygame/phaser-plugin-virtual-gamepad.js.erb"></script>

</head>

<body> -->

    <!-- Execution starts here -->
<!--     <script src="../assets/javascripts/rubygame/start.js.erb"></script>

</body>
</html> -->

fightingGame/app/views/welcome/show.html.erb
<head>
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

</head>


<section class="welcome-player">

<h1 class="game-title">Welcome to the King of Bartenders!</h1>
<p>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Join
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <span class="join-message">Please input your name and email address.</span>
    <div class="user-input">
      <!-- <form> -->
        <%= form_for :player, url: players_path do |f| %>
            Name: <%= f.text_field :name %>
            Email: <%= f.text_field :email %>
            <!-- submit button - ("Play"), after click- save the data to pg and link to controller page with correct params id. -->
            <%= f.submit "PLAY" %>
        <% end %>
      <!-- </form> -->
    </div>
  </div>
</div>

</section>